# Dockerfile.lambda
FROM public.ecr.aws/lambda/python:3.12

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ${LAMBDA_TASK_ROOT}/app/

CMD ["app.lambda_handler.lambda_handler"]